services:
  - type: web
    name: assignment3-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: MYSQL_HOST
        value: your-db-host
      - key: MYSQL_USER
        value: your-db-user
      - key: MYSQL_PASSWORD
        value: your-db-password
      - key: MYSQL_DB
        value: your-db-name
